/**
 * @param {import("knex").Knex} knex
 * @returns {Promise<void>}
 */
export async function seed(knex) {
    // Deletes ALL existing entries
    await knex("tariffs_box").del();

    // Inserts 30 seed entries with sample data
    await knex("tariffs_box").insert([
        // These are based on your provided Google Sheets data
        {
            date: "2025-08-19",
            warehouse_name: "Маркетплейс: Приволжский федеральный округ",
            geo_name: "Приволжский федеральный округ",
            box_delivery_coef_expr: 0,
            box_delivery_and_storage_expr: 200,
            box_storage_coef_expr: 0,
            box_delivery_liter: 0,
            box_storage_liter: 0,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Маркетплейс: Дальневосточный федеральный округ",
            geo_name: "Дальневосточный федеральный округ",
            box_delivery_coef_expr: 0,
            box_delivery_and_storage_expr: 155,
            box_storage_coef_expr: 0,
            box_delivery_liter: 0,
            box_storage_liter: 0,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Маркетплейс: Центральный федеральный округ СГТ",
            geo_name: "Центральный федеральный округ",
            box_delivery_coef_expr: 0,
            box_delivery_and_storage_expr: 75,
            box_storage_coef_expr: 100,
            box_delivery_liter: 0,
            box_storage_liter: 0.07,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Маркетплейс: Дальневосточный федеральный округ СГТ",
            geo_name: "Дальневосточный федеральный округ",
            box_delivery_coef_expr: 0,
            box_delivery_and_storage_expr: 100,
            box_storage_coef_expr: 100,
            box_delivery_liter: 0,
            box_storage_liter: 0.07,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Маркетплейс: Сибирский федеральный округ",
            geo_name: "Сибирский федеральный округ",
            box_delivery_coef_expr: 0,
            box_delivery_and_storage_expr: 200,
            box_storage_coef_expr: 0,
            box_delivery_liter: 0,
            box_storage_liter: 0,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Маркетплейс: Узбекистан",
            geo_name: "Узбекистан",
            box_delivery_coef_expr: 0,
            box_delivery_and_storage_expr: 155,
            box_storage_coef_expr: 0,
            box_delivery_liter: 0,
            box_storage_liter: 0,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Маркетплейс: Беларусь",
            geo_name: "Беларусь",
            box_delivery_coef_expr: 0,
            box_delivery_and_storage_expr: 155,
            box_storage_coef_expr: 0,
            box_delivery_liter: 0,
            box_storage_liter: 0,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Маркетплейс: Армения СГТ",
            geo_name: "Армения",
            box_delivery_coef_expr: 0,
            box_delivery_and_storage_expr: 100,
            box_storage_coef_expr: 100,
            box_delivery_liter: 0,
            box_storage_liter: 0.07,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Маркетплейс: Беларусь СГТ",
            geo_name: "Беларусь",
            box_delivery_coef_expr: 0,
            box_delivery_and_storage_expr: 100,
            box_storage_coef_expr: 100,
            box_delivery_liter: 0,
            box_storage_liter: 0.07,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Маркетплейс: Узбекистан СГТ",
            geo_name: "Узбекистан",
            box_delivery_coef_expr: 0,
            box_delivery_and_storage_expr: 100,
            box_storage_coef_expr: 100,
            box_delivery_liter: 0,
            box_storage_liter: 0.07,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Маркетплейс: Северо-Западный федеральный округ",
            geo_name: "Северо-Западный федеральный округ",
            box_delivery_coef_expr: 0,
            box_delivery_and_storage_expr: 200,
            box_storage_coef_expr: 0,
            box_delivery_liter: 0,
            box_storage_liter: 0,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Маркетплейс: Сибирский федеральный округ СГТ",
            geo_name: "Сибирский федеральный округ",
            box_delivery_coef_expr: 0,
            box_delivery_and_storage_expr: 100,
            box_storage_coef_expr: 100,
            box_delivery_liter: 0,
            box_storage_liter: 0.07,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Маркетплейс: Южный федеральный округ",
            geo_name: "Южный федеральный округ",
            box_delivery_coef_expr: 0,
            box_delivery_and_storage_expr: 160,
            box_storage_coef_expr: 0,
            box_delivery_liter: 0,
            box_storage_liter: 0,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Обухово СГТ",
            geo_name: "Центральный федеральный округ",
            box_delivery_coef_expr: 75,
            box_delivery_and_storage_expr: 75,
            box_storage_coef_expr: 75,
            box_delivery_liter: 7.13,
            box_storage_liter: 0.05,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Голицыно СГТ",
            geo_name: "Центральный федеральный округ",
            box_delivery_coef_expr: 75,
            box_delivery_and_storage_expr: 75,
            box_storage_coef_expr: 75,
            box_delivery_liter: 7.13,
            box_storage_liter: 0.05,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Шушары СГТ",
            geo_name: "Северо-Западный федеральный округ",
            box_delivery_coef_expr: 95,
            box_delivery_and_storage_expr: 95,
            box_storage_coef_expr: 95,
            box_delivery_liter: 9.03,
            box_storage_liter: 0.07,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Радумля СГТ",
            geo_name: "Центральный федеральный округ",
            box_delivery_coef_expr: 95,
            box_delivery_and_storage_expr: 95,
            box_storage_coef_expr: 95,
            box_delivery_liter: 9.03,
            box_storage_liter: 0.07,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Софьино СГТ",
            geo_name: "Центральный федеральный округ",
            box_delivery_coef_expr: 95,
            box_delivery_and_storage_expr: 95,
            box_storage_coef_expr: 95,
            box_delivery_liter: 9.03,
            box_storage_liter: 0.07,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Tbilisi 2",
            geo_name: "Грузия",
            box_delivery_coef_expr: 100,
            box_delivery_and_storage_expr: 100,
            box_storage_coef_expr: 100,
            box_delivery_liter: 9.5,
            box_storage_liter: 0.07,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Кузнецк СГТ",
            geo_name: "Приволжский федеральный округ",
            box_delivery_coef_expr: 100,
            box_delivery_and_storage_expr: 100,
            box_storage_coef_expr: 100,
            box_delivery_liter: 9.5,
            box_storage_liter: 0.07,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Челябинск СГТ",
            geo_name: "Уральский федеральный округ",
            box_delivery_coef_expr: 100,
            box_delivery_and_storage_expr: 100,
            box_storage_coef_expr: 100,
            box_delivery_liter: 9.5,
            box_storage_liter: 0.07,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Ярославль СГТ",
            geo_name: "Центральный федеральный округ",
            box_delivery_coef_expr: 100,
            box_delivery_and_storage_expr: 100,
            box_storage_coef_expr: 100,
            box_delivery_liter: 9.5,
            box_storage_liter: 0.07,
        },
        {
            date: "2025-08-19",
            warehouse_name: "SC Tbilisi",
            geo_name: "Грузия",
            box_delivery_coef_expr: 100,
            box_delivery_and_storage_expr: 100,
            box_storage_coef_expr: 100,
            box_delivery_liter: 9.5,
            box_storage_liter: 0.07,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Санкт-Петербург СГТ",
            geo_name: "Северо-Западный федеральный округ",
            box_delivery_coef_expr: 105,
            box_delivery_and_storage_expr: 105,
            box_storage_coef_expr: 105,
            box_delivery_liter: 9.98,
            box_storage_liter: 0.07,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Волгоград",
            geo_name: "Южный федеральный округ",
            box_delivery_coef_expr: 110,
            box_delivery_and_storage_expr: 110,
            box_storage_coef_expr: 110,
            box_delivery_liter: 10.45,
            box_storage_liter: 0.08,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Рязань (Тюшевское)",
            geo_name: "Центральный федеральный округ",
            box_delivery_coef_expr: 120,
            box_delivery_and_storage_expr: 120,
            box_storage_coef_expr: 140,
            box_delivery_liter: 11.4,
            box_storage_liter: 0.1,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Невинномысск",
            geo_name: "Северо-Кавказский федеральный округ",
            box_delivery_coef_expr: 130,
            box_delivery_and_storage_expr: 130,
            box_storage_coef_expr: 135,
            box_delivery_liter: 12.35,
            box_storage_liter: 0.09,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Сабурово",
            geo_name: "Центральный федеральный округ",
            box_delivery_coef_expr: 130,
            box_delivery_and_storage_expr: 130,
            box_storage_coef_expr: 130,
            box_delivery_liter: 12.35,
            box_storage_liter: 0.09,
        },
        {
            date: "2025-08-19",
            warehouse_name: "СЦ Тбилиси 3 Бонд",
            geo_name: "Грузия",
            box_delivery_coef_expr: 130,
            box_delivery_and_storage_expr: 130,
            box_storage_coef_expr: 0,
            box_delivery_liter: 12.35,
            box_storage_liter: 0,
        },
        {
            date: "2025-08-19",
            warehouse_name: "Атакент",
            geo_name: "Казахстан",
            box_delivery_coef_expr: 135,
            box_delivery_and_storage_expr: 135,
            box_storage_coef_expr: 115,
            box_delivery_liter: 12.83,
            box_storage_liter: 0.08,
        },
    ]);
}
